
var ufList = [
    {"display": "Acre","value": "AC"},
    {"display": "Alagoas","value": "AL"},
    {"display": "Amazonas","value": "AM"},
    {"display": "Amapá","value": "AP"},
    {"display": "Bahia","value": "BA"},
    {"display": "Ceará","value": "CE"},
    {"display": "Distrito Federal","value": "DF"},
    {"display": "Espírito Santo","value": "ES"},
    {"display": "Goiás","value": "GO"},
    {"display": "Minas Gerais","value": "MG"},
    {"display": "Mato Grosso do Sul","value": "MS"},
    {"display": "Mato Grosso","value": "MT"},
    {"display": "Pará","value": "PA"},
    {"display": "Paraíba","value": "PB"},
    {"display": "Pernambuco","value": "PE"},
    {"display": "Piauí","value": "PI"},
    {"display": "Paraná","value": "PR"},
    {"display": "Rio de Janeiro","value": "RJ"},
    {"display": "Rio Grande do Norte","value": "RN"},
    {"display": "Rondônia","value": "RO"},
    {"display": "Roraima","value": "RR"},
    {"display": "Rio Grande do Sul","value": "RS"},
    {"display": "Santa Catarina","value": "SC"},
    {"display": "Sergipe","value": "SE"},
    {"display": "São Paulo","value": "SP"},
    {"display": "Tocantins","value": "TO"},                
  ];